resources:
  - name: gitrepo_res
    type: gitRepo
    repoPath: kirtisahu05/sample_node
    configuration:
      integrationName: github-int
      branches:
        except: random
    initialVersion:
      sha: master

  - name: file_res
    type: file
    fileUrl: https://github.com/ankul-shippable/sample_java/blob/master/shippable.yml
    configuration:
      integrationName: github-int
    initialVersion:
      fileName: shippable.yml
      fileDtTm: random_value
 
  - name: image_res
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: docker-int
    initialVersion:
      imageTag: latest

pipelines:
  - name: pipe_1
    setup:
      runtime: onHost
    steps:
      - name: step1_A
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          runtime: onHost
        requires:
          integrations:
            - docker-int
          resources:
            - image_res
        triggeredBy:
          resources:
            - gitrepo_res 
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          - file_res

      - name: step1_B
        type: bash
        configuration:
          affinityGroup: test_group      
        setup:
          runtime: onHost
        triggeredBy:
          resources:
            - file_res 
        execution:
          onExecute:
            - echo "executing..."

      - name: step1_C
        type: bash
        configuration:
          affinityGroup: test_group      
        setup:
          runtime: onHost
        triggeredBy:
          steps:
            - step1_A 
        execution:
          onExecute:
            - echo "executing..."
